export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function HomeLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <header>Header</header>
      <nav>네비게이션</nav>
      <body>1 . HomeLayout :: {children}</body>
      <footer>Footer</footer>
    </html>
  );
}
